ORIGINAL_DESCRIPTION = u'originalName'
ORIGINAL_NAME = u'originalName'
DESCRIPTION = u'description'
PARENT_PATH = u'parentPath'
TAGS = u'tags'
TYPE = u'type'
TABLE_TYPE = u'TABLE'
FIELD_TYPE = u'FIELD'
DATA_TYPE = u'dataType'

HIGHLIGHT_INTERNAL_TYPE = u'internalType'
HIGHLIGHT_TYPE_HV_FIELD = u'<em>hv_field</em>'
HIGHLIGHT_TYPE_FIELD = u'<em>FIELD</em>'
HIGHLIGHT_TYPE_HV_TABLE = u'<em>hv_table</em>'
HIGHLIGHT_TYPE_TABLE = u'<em>TABLE</em>'